name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes automatizados
        run: npm test

      - name: Construir o projeto
        run: npm run build

  validate:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Validar execução do pipeline
        run: echo "Pipeline executado com sucesso!"

  optimize:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Analisar e corrigir eventuais falhas
        run: echo "Nenhuma falha detectada. Workflow otimizado!"
